### ISSUE TITLE
Possibly add compute env info

### ISSUE THREAD

**Issue by amsnyder** [SimonTopp/drb_generalizability_data_release#10]
Based on the[ Native Data Set Environment info](https://github.com/SimonTopp/drb_generalizability_data_release/blob/a0a7fe648f5b002c6453a6a1e094935a9fd7febc/in_text/text_data_release.yml#L19) you provided in the metadata file, I would assume that I can run this on my local computer. Is that true? If you ran your code in the cloud or on an HPC, I would request some more info on the environment you used.

**Comment by SimonTopp** [comment]
You can indeed run this all locally or on HPC!  Environment yamls and Readme instructions in the data prep and modeling code walk through how to set up and run everything.  I've added a note to this extent in the [Native Data Set Environment Info.](https://github.com/SimonTopp/drb_generalizability_data_release/blob/d10c4371bfe08af09324f847362e312da26a3466/in_text/text_data_release.yml#L19-L21)
