### ISSUE TITLE
spatial metadata missing

### ISSUE THREAD

**Issue by amsnyder** [SimonTopp/drb_generalizability_data_release#12]
Hey Simon - looks like some required spatial metadata is missing here. It gets created by the `extract_features` function (which you can see in the template [here](https://github.com/USGS-R/slim-data-release-template/blob/f4358e16f3786ada26326cae0535b1cfdbf10608/remake.yml#L19).

You just need to identify a shapefile that can be used to represent the spatial area of this work - it could be a polygon of the DRB, some river network lines, etc. You will want to upload this file to Caldera, where you've set up this model archive pipeline, add in the function(s) to read in the data and `extract_features` like you see in the example, then re-run the pipeline to update the metadata.

Let me know when you've made this update, and I'll recheck the metadata.

**Comment by SimonTopp** [comment]
Sounds good! I'll knock this out tomorrow.

**Comment by SimonTopp** [comment]
Ok, spatial metadata has been updated and is now in the xml file.

**Comment by amsnyder** [comment]
Thanks! Spatial metadata looks good now. Did you mean to post the file to SB here? https://github.com/SimonTopp/drb_generalizability_data_release/blob/1f952f93f8c7799331960ea40d1661a7ae9ef5f3/remake.yml#L49

**Comment by SimonTopp** [comment]
The slim release template does include it to be posted, but looking at a couple complete releases it looks like it gets removed before things are finalized. I'll go ahead and remove it. Maybe there's a reason it's posted in the template? If not lets update the template to avoid confusion.

**Comment by amsnyder** [comment]
The template was set up assuming someone has spatial data files as part of their release. Your release doesn't have any spatial data files, which is why you need to do this "dummy" file thing. I just merged a PR this morning that added a comment hopefully explaining that: https://github.com/USGS-R/hierarchical-data-release-template/blob/0989c36af3b88139a87b769f05826165772e1e71/1_spatial.yml#L19

Let me know if you think it needs anything added/changed to help make this clear!

**Comment by amsnyder** [comment]
I added that change to the slim template too!

**Comment by SimonTopp** [comment]
Perfect! That looks good to me. I also looked over the updated DSP manual this morning, these comments and those updates overall make things much clearer than when I started on this release. Nice job 🙌💯
