### ISSUE TITLE
Delete cache files

### ISSUE THREAD

**Issue by amsnyder** [SimonTopp/drb_generalizability_data_release#5]
You might want to consider deleting the following files, just to keep your model archive a little more tidy:
- __pycache__
- .ipynb_checkpoints
- .git
- .idea
- .snakemake
- .DS_Store
- .Rhistory
- .gitignore (while this is actually a useful file, I am not sure if it adds value to the archive, but I don't feel as strongly about deleting this one)

I definitely wouldn't say you have to remove them, but it would keep things a little cleaner and easier to get oriented.

I also see that `02_Model_Code\river-dl\workflow_examples` only has a `.snakemake` folder in it. Should more content be in here? Should this folder be deleted?

**Comment by SimonTopp** [comment]
Gah! Hidden files!! Good catch, I've gone ahead and deleted these (left .gitignore though).  `02_Model_Code\river-dl\workflow_examples` should have 4-5 `.yml` and `.smk` files in it.  Not sure why those didn't get zipped, I'll look into it.

**Comment by SimonTopp** [comment]
Ok, not sure what was up the first time, but when I just re-zipped everything the `workflow examples` folder zipped correctly.
