### ISSUE TITLE
Updates to entitiy and attribute information

### ISSUE THREAD

**Issue by amsnyder** [SimonTopp/drb_generalizability_data_release#6]
The following files aren't in entity and attribute information, so you might want to add them:
- 01_Data_Prep\river-dl_data_prep\ChristianaReaches
- 01_Data_Prep\river-dl_data_prep\River_dl_dataPrep
- 03_Model_Predictions\results\xai_outputs

Are the scripts in `02_Model_Code\river-dl\river_dl\` documented anywhere? I think it's ok to not document every script, as long as a user at least understands how to run them - which touches on another issue I will open.

**Comment by SimonTopp** [comment]
Running `River-dl` is all documented in the `README.md`.  The `river_dl` folder is a module that only contains functions that are called from the Snakemake workflows. So there aren't any full-on, run-able scripts in `river_dl`.  I do need to do another once over on the README.md to make sure it's complete and appropriate for the release though.
