### ISSUE TITLE
Add README.md files

### ISSUE THREAD

**Issue by amsnyder** [SimonTopp/drb_generalizability_data_release#8]
I just skimmed your README.md and Snakefile in 01_Data_Prep quickly, so correct me if I'm wrong here, but I think those files only run the data prep piece of the pipeline. If that's the case, could you add instructions for the code in 02_Model_Code?

**Comment by SimonTopp** [comment]
There is another README.md in 02_Model_Code that outlines running the training routines.  I've made this explicit in the `build-environment` and the `abstract` of the release
