### ISSUE TITLE
Making the code runnable with file reorganization.

### ISSUE THREAD

**Issue by amsnyder** [SimonTopp/drb_generalizability_data_release#9]
The idea of this model archive is that a reader will be able to rerun your model code. I think the Snakefile filepaths might need to be updated based on the file structure you've used in the archive, but I could be wrong because I haven't tried to run it yet.

This relates to another question I have - should I try to run this model? Ideally, as a reviewer, I would run the code to make sure it all works. How long does it take to run? Can I run it locally? If I cannot perform this part of the review, I'll need to take some notes about why I couldn't do it.

**Comment by SimonTopp** [comment]
Yes! You should be able to run it (either locally or on TG).  Instructions are in the `README.md`.  I'll go through again and make sure it's very clear and filepaths are all correct. Right now I think its set up where you need to move the Snakemake you want into your run directory, but I'll update so you can just run everything from where it is.

**Comment by SimonTopp** [comment]
Updated all paths so you should be able to run everything with existing paths.  Updated README as well for clarity.
